src/com/haku/model/Account.java
package com.haku.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "account")
public class Account {

	private String email;
	private String passwrod;

	public Account() {
		super();
	}

	@Id
	@Column(name = "email")
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", length = 255, nullable = false)
	public String getPasswrod() {
		return passwrod;
	}

	public void setPasswrod(String passwrod) {
		this.passwrod = passwrod;
	}

}

src/com/haku/model/Config.java
package com.haku.model;

public class Config {
	public static final String HISTORY_TABLE = "history";
	public static final String FARVERITE_TABLE = "farverite";
}

src/com/haku/model/DBconnector.java
package com.haku.model;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class DBconnector {

	private static DBconnector instance = new DBconnector();

	private DBconnector() {

	}

	public static DBconnector getInstance() {
		return instance;
	}

	public Connection getConnecion() {
		Connection connection = null;
		String dbUrl = "jdbc:mysql://localhost:3306/shortstory";
		String dbUserName = "root";
		String dbPassWord = "buiquangcuong";
		try {

			Class.forName("com.mysql.cj.jdbc.Driver");
			connection = DriverManager.getConnection(dbUrl, dbUserName, dbPassWord);
		} catch (ClassNotFoundException e) {
			System.out.println("Connect DB: Error");
			e.printStackTrace();
		} catch (SQLException e) {
			System.out.println("Connect DB: Error");
			e.printStackTrace();
		}
		return connection;

	}

	public static boolean closeConnection(Connection connection) {
		if (connection == null)
			return false;
		try {
			connection.close();
			return true;
		} catch (SQLException e) {
			e.printStackTrace();
			System.out.println("close connection: Error");
		}
		System.out.println("close connection: Error");
		return false;

	}

}

src/com/haku/model/StoryProperties.java
package com.haku.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
@Entity
@Table(name = "history")
public class StoryProperties {

	private int id;
	private String title;
	private String content;
	private String img_url;
	
	
	
	public StoryProperties() {
	}
	public StoryProperties(String title, String content, String img_url) {
		
		this.title = title;
		this.content = content;
		this.img_url = img_url;
	}
	public StoryProperties(int id,String title, String content, String img_url) {
		this.id = id;
		this.title = title;
		this.content = content;
		this.img_url = img_url;
	}
	
	@Id
	@Column(name="id")
	@GeneratedValue(strategy=GenerationType.AUTO)
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
	@Column(name="title")
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	@Column(name="content")
	public String getContent() {
		return content;
	}
	
	public void setContent(String content) {
		this.content = content;
	}
	
	@Column(name="image_url")
	public String getImg_url() {
		return img_url;
	}

	public void setImg_url(String img_url) {
		this.img_url = img_url;
	}

	public void check() {
		System.out.println(id);
		System.out.println(title);
		System.out.println(content);
		System.out.println(img_url);
	}

}

src/com/haku/model/Temp.java
package com.haku.model;

public class Temp {

	private String name;
	private int number;
	private String name_x;

	public Temp() {
	}

	public Temp(String name, int number) {
		this.name = name;
		this.number = number;
	}

	public Temp(String name, int number, String name_x) {
		this.name = name;
		this.number = number;
		this.name_x = name_x;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getNumber() {
		return number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	public String getName_x() {
		return name_x;
	}

	public void setName_x(String name_x) {
		this.name_x = name_x;
	}
	
}

src/com/haku/controller/AccountController.java
package com.haku.controller;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import com.haku.model.Account;
import com.haku.service.AccountService;

@SuppressWarnings("deprecation")
@ManagedBean(name = "accountController")
@SessionScoped
public class AccountController {
	private Account account = new Account();
	private AccountService accountService = new AccountService();
	private String register;
	private String hasError;

	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getRegister() {
		return register;
	}

	public void setRegister(String register) {
		this.register = register;
	}

	public String login() {
		if (register.equals("true")) {
			boolean check = accountService.registerEmail(account);
			if (check)
				hasError = "Success";
			else {
				System.out.println("log");
				hasError = "account already exists";
			}
		} else {
			if (accountService.authenticAccount(account)) {
				return "home";
			} else {
				hasError = "Incorrect username or password";
			}
		}
		return "login";
	}

	public String logout() {
		hasError = "";
		return "login";
	}

	public String getHasError() {
		return hasError;
	}

	public void setHasError(String hasError) {
		this.hasError = hasError;
	}

}

src/com/haku/controller/HomeController.java
package com.haku.controller;

import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import org.hibernate.Session;
import org.hibernate.SessionFactory;

import com.haku.hibernate.HibernateUtils;
import com.haku.model.StoryProperties;
import com.haku.service.ReaderHibernateDemo;
import com.haku.service.ReaderService;
import com.haku.service.TypeStoryService;

@SuppressWarnings("deprecation")
@ManagedBean(name = "homeController")
@SessionScoped
public class HomeController {

	private String currentType;
	private StoryProperties currentStory;
	private ReaderService readerService = new ReaderService();

	public String getCurrentType() {
		return currentType;
	}

	public void setCurrentType(String currentType) {
		System.out.println("Current type");
		this.currentType = currentType;
	}

	public String getPage() {
		return "liststory";
	}

	public String getPageHistory() {
		currentType = "Lịch sử đọc";
		return "liststory";
	}

	public ArrayList<StoryProperties> getListStory() {
		ArrayList<StoryProperties> list = readerService.getListHF(TypeStoryService.getTableName(currentType));
		return list;
	}

	public StoryProperties getCurrentStory() {
		return currentStory;
	}

	public void setCurrentStory(StoryProperties currentStory) {
		System.out.println("================================ " + currentStory.getTitle());
		this.currentStory = currentStory;
		readerService.insertStory(currentStory, "history");
	}

	public void InsertToHistory(StoryProperties properties) {
		readerService.insertStory(properties, "history");
		
	}
}

src/com/haku/controller/TypeController.java
package com.haku.controller;

import java.util.ArrayList;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import com.haku.model.Temp;
import com.haku.service.TypeStoryService;

@SuppressWarnings("deprecation")
@ManagedBean
@SessionScoped
public class TypeController {

	private TypeStoryService typeStoryService = new TypeStoryService();
	public ArrayList<Temp> getType() {
		ArrayList<Temp> listType_of_story = typeStoryService.getType();
		return listType_of_story;
	}
}

WebContent/home.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
	<title>Truyện ngắn</title>
	
</h:head>

<h:body>
	<ui:include src="nav.xhtml"></ui:include>
	<h:form>
		<table border="1" style="margin: auto;">
			<tr>
				<th>Thể loại</th>
				<th>Số lượng</th>
			</tr>
			<ui:repeat var="type" value="#{typeController.type}">
				<tr>
					<td><h:commandLink action="#{homeController.getPage}"
							actionListener="#{homeController.setCurrentType(type.name)}">#{type.name}</h:commandLink></td>
					<td>#{type.number}</td>
				</tr>
			</ui:repeat>
		</table>
	</h:form>
</h:body>

</html>

WebContent/index.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<head>
</head>
<body>
	
	<h1 align="center">Người yêu cũ có người yêu mới</h1>
	<div class="maincontent">
		<p style="text-align: justify;">
			<strong>Ai đó nói với em rằng: "Ngày đầu tiên chia tay,
				người cũ là tất cả. Ngày thứ hai trở lại là một nửa. Ngày thứ ba còn
				một phần tư. Và cứ thế giảm dần theo cấp số nhân cho đến mãi mãi.
				Nhưng theo quy luật của Toán học, dẫu chia đến vô cùng lần vẫn không
				thể bằng 0 nên người cũ không bao giờ là không gì cả...".</strong>
		</p>
		<p style="text-align: justify;">
			<strong> Vì không bao giờ là không gì cả, nên khi người cũ
				có người mới, cảm giác buồn là thật, nhói lòng cũng là thật, bi
				thương cũng là thật.</strong>
		</p>
		<p style="text-align: center;">
			<strong>***</strong>
		</p>
		<p style="text-align: center;">
			<strong><img
				src="http://www.truyenngan.com.vn/images/Phuongvtm/2016-02/nguoi-yeu-cu-co-nguoi-yeu-moi.jpg"
				width="500" height="325" alt="nguoi-yeu-cu-co-nguoi-yeu-moi"></img></strong>
		</p>
		<p style="text-align: justify;">Ta không bao giờ chọn lựa cô đơn
			và có muôn vàn lý do cho sự đổ vỡ. Chỉ là không thể ở bên nhau dài
			lâu, chỉ là có nhiều mỏi mệt, chỉ là mỗi ngày yêu đương đều có những
			nỗi buồn vô cớ túm lấy nhau một cách khó nhọc. Vì thế chúng ta quyết
			định chia xa, quyết định tạm thời không có nhau bên đời nữa, quyết
			định rời xa "một nửa" của mình, để rồi khi trái tim ấy tìm thấy mảnh
			ghép khác, vẫn thấy có gì như mất mát, vẫn thấy có gì như ghen tỵ.</p>
		<p style="text-align: justify;">Không ghen tỵ sao được khi bàn tay
			ấy đã từng là của mình, bờ vai ấy đã từng là của mình, vòng ôm đó đã
			từng là của mình, nụ hôn nồng nhiệt ấy đã từng dành cho mình mà bây
			giờ bỗng thành của người khác...</p>
		<p style="text-align: justify;">Con người luôn ích kỷ như thế,
			những ngọt ngào của tình yêu, dù đã cũ, nhưng vẫn không thích nó sẽ
			thuộc về ai đó, không phải mình. Rồi có khi nào tự hỏi, người mới kia
			có được người-cũ-của-mình dắt tay qua những con đường, qua những phố
			cũ, được ngồi hàn huyên, cầm cốc trà nóng thật ấm lòng? Nghĩ về những
			điều mênh mang ấy, lại có gì như xót xa, lại có gì như xao xuyến, lại
			có gì như ước mong...</p>
		<p style="text-align: justify;">Khi người yêu cũ có người yêu mới,
			ta không thể thản nhiên mà gửi họ một lời chào, một lời chúc hạnh
			phúc, coi như không có chuyện gì cả. Ta ngắm nghía những bức ảnh chụp
			chung, những món quà nhỏ xíu, nhớ nụ cười tít mắt đến là vui lạ. Lại
			có lúc vu vơ post những status, những bài hát buồn tênh để mong người
			ấy có thể nghe thấy, rồi hoài niệm như là một điều duy nhất có thể
			bấu víu vào.</p>
		<p style="text-align: justify;">Bởi vì không thể quên, nên những
			vết yêu cũ ùa về không báo trước. Một người mình từng gắn bó giờ đã
			xa thật, một người mình cùng chung niềm ước mơ đã không còn bên cạnh
			nữa, một người mình từng tựa vai nhau rồi "mơ về ngôi nhà và những
			đứa trẻ", giờ đang bước cùng người khác trên con đường quen thuộc,
			quả thực không cam tâm nhưng vẫn phải chấp nhận.</p>
		<p style="text-align: justify;">Rồi ai cũng phải bước qua tổn
			thương để đi tiếp, rồi ai cũng có người để chở che, nhưng chắc hẳn ta
			sẽ không bao giờ quên được, người cũ luôn là một góc nhỏ trong trái
			tim ta, để mỗi khi bắt gặp một điều gì quen thuộc, ta sẽ cười bình
			yên cho những điều xưa cũ.</p>
		<p style="text-align: justify;">Người yêu cũ có người yêu mới, có
			niềm vui mới, có hạnh phúc mới. Còn ta gặm nhấm những niềm vui đã
			qua, những hạnh phúc đã qua, những nhớ nhung đã qua như một cách để
			ta đối xử tốt với bản thân mình, với tình yêu mà ta đã từng xem như
			hơi thở.</p>
		<p style="text-align: justify;">Người yêu cũ à, đừng quên hết mảnh
			ký ức đã qua...</p>
		<p style="text-align: justify;">
			<strong>Ngọc Vũ</strong>
		</p>
		<p style="text-align: justify;">
			<strong>#Tobi</strong>
		</p>
	</div>

	
	
	
</body>
</html>

WebContent/liststory.xhtml
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
	<title>#{homeController.currentType}</title>
</h:head>
<h:body>
	<ui:include src="nav.xhtml"></ui:include>
	<h:form>
		<table border="1" style="margin: auto; column-count: 3;">
			<ui:repeat var="item" value="#{homeController.listStory}">
				<tr>
					<td><h:commandLink action="reader"
							actionListener="#{homeController.setCurrentStory(item)}">#{item.title}</h:commandLink></td>
				</tr>
			</ui:repeat>
		</table>
	</h:form>
</h:body>
</html>

WebContent/login.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core">
<h:head>
	<style type="text/css">
.form-signin {
	max-width: 330px;
	padding: 15px;
	margin: 0 auto;
}
</style>

	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<meta http-equiv="X-UA-Conpatible" content="IE=edge" />


	<title>Login</title>
	<h:outputScript name="js/jquery-3.1.0.min.js" />
	<h:outputScript name="js/bootstraps.min.js" />
	<h:outputStylesheet library="css" name="bootstrap.min.css" />
	<h:outputStylesheet library="css" name="bootstrap-theme.min.css" />

</h:head>
<h:body>
	<div class="container">
		<h:form class="form-signin">
			<h2 class="form-signin-heading">Please sign in</h2>
		User Name: <h:inputText id="username"
				value="#{accountController.account.email}" required="true"
				class="form-control" />
			
		Password:  <h:inputSecret id="password"
				value="#{accountController.account.passwrod}" required="true"
				class="form-control" />
			
		Register  <h:selectBooleanCheckbox id="register"
				value="#{accountController.register}" />
			<br></br>
			<h:commandButton value="sumbit" action="#{accountController.login}"
				class="btn btn-lg btn-primary btn-block" />
			<H3>#{accountController.hasError}</H3>
		</h:form>
	</div>
</h:body>

</html>

WebContent/nav.xhtml
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:form style="margin-right: 1000px">
	<h:commandButton value="Logout" action="#{accountController.logout}" ></h:commandButton>
	<h:commandButton value="history" action="#{homeController.getPageHistory}"></h:commandButton>
	<h:commandButton value="home" action="home"></h:commandButton>
</h:form>
</html>

WebContent/reader.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>


</h:head>

<h:body>
		<ui:include src="nav.xhtml"></ui:include>
		#{homeController.currentStory.title}
		<br></br>
		<h:graphicImage value="#{homeController.currentStory.img_url}"></h:graphicImage>
</h:body>
</html>